/* Create a class Account having private instance member Id, Name Balanceamt.
 * Id should be generated by application. 
 * Create method deposit who’s job is to increase Balanceamt by the amout deposited by account holder. 
 * Create method withdraw who’s job is to decrease Balanceamt by the amount  withdrawn by account holder.
 * Write method display which will display name and Balanceamt. 
 * Your application should generate only 3 object, if you try to generate 4 th object it should display message can not create object. 
 * This application will be classlibrary.
Create console application and use this class library. 
 * Create at least two object of account class and deposit and withdraw money. */


using System;

namespace AccountLib5_2
{
    public class Account
    {
        private int id;
        private string name;
        private double balanceAmt;

        public static int ID=0;

        static Account()
        {
            Console.WriteLine("Welcome to SADABAND BANK");
        }
        public Account(string nm, double bal)
        {
            if (ID <= 2)
            {
                this.id = ++ID;
                this.name = nm;
                this.balanceAmt = bal;
            }
            else
                throw new Exception("Only 3 Accounts can be created");
        }

        public void deposite(int amt)
        {
            this.balanceAmt +=  amt;
            Console.WriteLine("Successfully deposited Rs. " + amt);
        }

        public void withdraw(int amt)
        {
            if ((balanceAmt - amt) > 0)
            {
                this.balanceAmt -= amt;
                Console.WriteLine("Successfully Deducted Rs. " + amt);
            }
            else
                throw new Exception("Insufficient balance in Account");
        }

        public void display()
        {
            Console.WriteLine("{0} your account balance is {1}",name,balanceAmt);
        }
    }
}
