/* Create a class school, having array of student object. 
 * Create a class student having member variable rollnumber, name, marks .
 * rollnumber should be generated by application. 
 * When you load application display school name.
 * Display all student name and marks. */

using System;
using System.Collections;


namespace Day10_2
{
    
    class Student
    {
        public string Name { get; set; }
        public int Marks { get; set; }
        public int rollno;
        GetRoll rollobj = new GetRoll();
        public Student() {  }
        public Student(string name, int marks)
        {
            Name = name;
            Marks = marks;
            this.rollno = rollobj.GetRollNo();
        }
    }

    class GetRoll
    {
        static int rollno = 0;
        public int GetRollNo()
        {
          //  Console.WriteLine("hii"+rollno);
            return ++rollno;
        }
    }

    class School : IEnumerable
    {
        static School() { Console.WriteLine("Welcome to VITA\n\n"); }

        Student[] s=new Student[3];
        public School()
        {
            s[0] = new Student("Ajay", 62);
            s[1] = new Student("Vijay",95);
            s[2] = new Student("Sujay",59);
        }
        public IEnumerator GetEnumerator()
        {
            return s.GetEnumerator();
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            School s1 = new School();
            Console.WriteLine("Printing Using Foreach");
            foreach (Student s in s1)
            {
                Console.WriteLine("{0} {1} {2}",s.rollno, s.Name, s.Marks);
            }

            Console.WriteLine("Printing Using IEnumerator");
            IEnumerator i = s1.GetEnumerator();
            while (i.MoveNext())
            {
                Student s2 = (Student)i.Current;
                Console.WriteLine("{0} {1} {2}", s2.rollno, s2.Name, s2.Marks);
            }
        }
    }
}
